accounts/urls.py
from django.conf.urls import url
from .views import (
    login_view, register_view,
)

urlpatterns = [
    url(r"^login/$", login_view, name = "login"),
    url(r"^register/$", register_view, name = "register"),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import Dashboard

urlpatterns = [
    path('', Dashboard.as_view(), name='index'),
]

u_tube/urls.py
from django.urls import path
from u_tube.views import Index, VideoDetail
from django.conf.urls import url

urlpatterns = [
    path('', Index.as_view(), name='list'),
    path('<int:video_id>/', VideoDetail.as_view(), name='detail'),
]

utube/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include(("u_tube.urls", "u_tube"), namespace='videos')),
    path('dashboard/',include(("dashboard.urls", "dashboard"), namespace='dashboard')),
    url(r'^logout/$',auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(("accounts.urls","accounts"), namespace="accounts")),
    url(r'^$', login_required(TemplateView.as_view(template_name="u_tube/video_list.html"))),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

u_tube/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Video(models.Model):
    title = models.CharField(null=False, max_length=255)
    description = models.TextField(null=True, blank=True)
    video = models.FileField(upload_to='videos/')
    thumbnail = models.FileField(upload_to='video_thumb/', default='')
    pub_date = models.DateTimeField(default=now())  

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth import authenticate
from django import forms


class UsersLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput, )

    def __init__(self, *args, **kwargs):
        super(UsersLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name": "username"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name": "password"})

    def clean(self, *args, **keyargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("User is no longer active")

        return super(UsersLoginForm, self).clean(*args, **keyargs)


from django.contrib.auth import authenticate, get_user_model
from django import forms

User = get_user_model()


class UsersRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "confirm_email",
            "password",
        ]

    username = forms.CharField()
    email = forms.EmailField(label="Email")
    confirm_email = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UsersRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            "name": "username"})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            "name": "email"})
        self.fields['confirm_email'].widget.attrs.update({
            'class': 'form-control',
            "name": "confirm_email"})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            "name": "password"})

    def clean(self, *args, **keyargs):
        email = self.cleaned_data.get("email")
        confirm_email = self.cleaned_data.get("confirm_email")
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if email != confirm_email:
            raise forms.ValidationError("Email must match")

        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("Email is already registered")

        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("User with this username already registered")

        # you can add more validations for password

        if len(password) < 8:
            raise forms.ValidationError("Password must be greater than 8 characters")

        return super(UsersRegisterForm, self).clean(*args, **keyargs)

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse

from .forms import UsersLoginForm, UsersRegisterForm


def login_view(request):
    form = UsersLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect(reverse("videos:list"))
    return render(request, "accounts/form.html", {
        "form": form,
        "title": "Login",
    })


def register_view(request):
    form = UsersRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        password = form.cleaned_data.get("password")
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        return redirect("/accounts/login")
    return render(request, "accounts/form.html", {
        "title": "Register",
        "form": form,
    })

dashboard/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
class Dashboard(generic.TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["dashboard_active"] ="active"
        return context   

u_tube/views.py
from django.shortcuts import render
from django.views import generic
from u_tube.models import Video
# Create your views here.

class Index(generic.ListView):
    template_name = 'templates/u_tube/video_list.html'
    model = Video
    context_object_name = 'videos'
    ##queryset = Video.objects.filter(title__contains = 'sample')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["video_active"] ="active"
        return context


class VideoDetail(generic.DetailView):
    template_name = 'u_tube/video_detail.html'
    model = Video
    pk_url_kwarg = 'video_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["video_active"] ="active"
        return context

accounts/templates/accounts/form.html
<!DOCTYPE html>
{% extends "u_tube/base.html" %}
{% block content %}
  <style type="text/css">
    .wrapper {
      margin-top: 80px;
      margin-bottom: 80px;
      -webkit-box-shadow: 3px 10px 18px 7px rgba(0, 0, 0, 0.24);
      -moz-box-shadow: 3px 10px 18px 7px rgba(0, 0, 0, 0.24);
      box-shadow: 3px 10px 18px 7px rgba(0, 0, 0, 0.24);
    }

    .form-signin {
      padding: 15px 35px 45px;
      margin: 0 auto;
      background-color: #fff;
      border: 1px solid rgba(0, 0, 0, 0.1);

    .form-signin-heading,
    .checkbox {
      margin-bottom: 30px;
    }

    .checkbox {
      font-weight: normal;
    }

    .form-control {
      position: relative;
      font-size: 16px;
      height: auto;
      padding: 10px;
    @include box-sizing(border-box);

    &
    :focus {
      z-index: 2;
    }

    }
    input[type="text"] {
      margin-bottom: -1px;
      border-bottom-left-radius: 0;
      border-bottom-right-radius: 0;
    }

    input[type="password"] {
      margin-bottom: 20px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }

    }
    @media (max-width: 500px) {
      footer {
        height: 130px !important;
        padding-bottom: 10px;
        padding-top: 10px;
      }
    }

    .container {
      display: flex;
      justify-content: center;
      margin-top: 50px;
    }
  </style>


  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <div class="wrapper">
        <form class="form-signin" method='POST' action='' enctype="multipart/form-data"
              style="margin-top: -30px; margin-bottom: -18px;">{% csrf_token %}
          <h2 class="form-signin-heading">{{ title }}</h2>
          {{ form.as_p }}
          </label><br>
          <button class="btn btn-lg btn-primary btn-block" type="submit">{{ title }}</button>
          <br>
          {% if title == "Login" %}<h5>Not Registered? <a href="/accounts/register">Register Here</a></h5>{% endif %}
          {% if title == "Register" %}<h5>Already Registered? <a href="/accounts/login">Login Here</a></h5>{% endif %}
        </form>

      </div>
    </div>
  </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'u_tube/base.html' %}

{% block content %}
  <style>
    .chart {
      display: flex;
    }

    .card-text {
      font-size: xxx-large;
    }

    .proper {
      display: flex;
      gap: 30px;
      justify-content: center;
    }
  </style>
  <div class="alert alert-success" role="alert">
    Hey, welcome {{ user.username }} to the dashboard section here you can see your videos status
  </div>
  <div class="proper">
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Total Views</h5>
            <span class="badge badge-secondary">
          <p class="card-text">1.73K</p></span>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Total Likes</h5>
            <span class="badge badge-secondary">
          <p class="card-text">1.46K</p></span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Subscribers</h5>
            <span class="badge badge-secondary">
          <p class="card-text">7.42K</p></span>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Subscribers+</h5>
            <span class="badge badge-secondary">
            <p class="card-text">542<i class="fa fa-arrow-circle-up" aria-hidden="true"></i></p></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="chart">
      <div>
        <canvas id="Video-views" width="600" height="400"></canvas>
      </div>
      <div>
        <canvas id="bar-chart-horizontal" width="600" height="400"></canvas>
      </div>
    </div>
  </div>
  <script>
    new Chart(document.getElementById("bar-chart-horizontal"), {
      type: 'horizontalBar',
      data: {
        labels: ["Robert arm", "Big bunny", "Sample1", "Sample2"],
        datasets: [
          {
            label: "Liked ",
            backgroundColor: ["green", "orange", "purple", "navy"],
            data: [128, 763, 357, 216]
          }
        ]
      },
      options: {
        legend: {display: false},
        title: {
          display: true,
          text: 'Most liked videos'
        }
      }
    });
    // Bar chart
    new Chart(document.getElementById("Video-views"), {
      type: 'line',
      data: {
        labels: [0, 100, 200, 300, 40, 500, 600, 700, 800],
        datasets: [{
          data: [0, 86, 99, 104, 106, 107, 111, 133],
          label: "Robert arm",
          borderColor: "green",
          fill: false
        }, {
          data: [0, 282, 350, 411, 502, 635, 809, 947],
          label: "Big bunny",
          borderColor: "orange",
          fill: false
        }, {
          data: [0, 168, 170, 178, 190, 203, 276, 408],
          label: "Sample1",
          borderColor: "purple",
          fill: false
        }, {
          data: [0, 10, 16, 16, 20, 24, 38, 279],
          label: "Sample2",
          borderColor: "navy",
          fill: false
        }
        ]
      },
      options: {
        title: {
          display: true,
          text: 'videos views'
        }
      }
    });
  </script>
{% endblock %}

u_tube/templates/u_tube/base.html
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script src="https://use.fontawesome.com/6ae7bfedd6.js"></script>


<style>
    body{
        font-family: 'Open Sans', sans-serif;
    }
    .nav-container{
        display:flex;
        justify-content:space-between;
        align-items:baseline;
    }
    .greeting{
        display:flex;
        flex-display:row;
        gap:5px;

    }
    .container-fluid{
        margin-top:10px;
    }
</style>
<body>
   <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
    <div class="container-fluid">
    <div class="nav-container" >
    <ul class="nav nav-pills" style="margin-bottom: 20px;">
  <li class="nav-item">
    <a class="nav-link {{ video_active }}" href="{% url 'videos:list' %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {{ dashboard_active }}" href='{% url 'dashboard:index' %}'>Dashboard</a>
  </li>
</ul>  
    <div class="greeting">
   {% if user.is_authenticated %}
        <p>Welcome {{ user.username }}</p>
        <a href="{% url 'logout' %}">logout</a>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'accounts:login' %}">login</a>
    {% endif %}
    </div>
    </div>

   {% block content %}
    {% endblock %}
    </div>
</body>

u_tube/templates/u_tube/video_detail.html
{% extends 'u_tube/base.html' %}
{% block content %}
  <div>
    <video width="640" height="360" controls>
      <source src="{{ object.video.url }}" type="video/mp4">
    </video>
  </div>
  <h1></h1>
  <div><font size="+20">
    <b>{{ object.title.upper }}{{ MEDIA_URL }}</b></font></div>
  <h3> description:</h3>
  {{ object.description }}
  <div>
    Date: {{ object.pub_date }}
  </div>
{% endblock %}

u_tube/templates/u_tube/video_list.html
{% extends 'u_tube/base.html' %}
{%block content %}
<style>
    .video-list-container{
        display:flex;
        flex-direction: row;
        }
    .video-list-container .item a{
        display:flex;
        flex-direction:column;
        gap : 10px;
        margin-right: 15px;
        text-decoration: none;
        font-weight: 600;
        color: #1f1f1f;
        padding-right: 15px;
        
    }    
    .video-list-container .item .title{
        font-size: 1.4rem;
        line-height: 2rem;
        max-height: 4rem;
        -webkit-box-orient: vertical;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: normal;
        -webkit-line-clamp: 2;
        
    }
</style>
<h1>Videos</h1>
<div class="video-list-container">
{% for video in videos %}
    <div class="item">
        <a href ='{% url 'videos:detail' video.id %}'>
            {% if video.thumbnail %}
                <img src="{{ video.thumbnail.url }}"class="img-thumbnail"style="width:480px;height:200px;"/>
            {% endif %}
            <div class="title">{{ video.title | capfirst }}</div>
        </a>
    </div>
{% empty %}
    <div>No Videos yet.</div>
{% endfor %}

</div>
{% endblock %}